---

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Enable default Nginx reverse proxy
  ansible.builtin.template:
    src: default.conf.j2
    dest: "/etc/nginx/sites-enabled/default"
    mode: "0644"
  notify: reload nginx
