---

- name: Clone React app from GitHub
  ansible.builtin.git:
    repo: "{{ portfolio_repo_url }}"
    dest: "{{ portfolio_clone_path }}"
    version: "{{ portfolio_branch }}"
    clone: yes
    update: yes
    force: yes

- name: "Deploy .env file"
  ansible.builtin.template:
    src: ".env.j2"
    dest: "{{ portfolio_clone_path }}/.env"
    owner: "{{ new_admin_user }}"
    group: "{{ new_admin_user }}"
    mode: "0644"

- name: Install nvm
  ansible.builtin.shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash"

- name: Run build
  ansible.builtin.shell: |
    source $HOME/.nvm/nvm.sh
    nvm install v20.17.0
    npm install
    npm run build
  args:
    chdir: "{{ portfolio_clone_path }}"
    executable: /bin/bash

- name: Copy Build to Nginx directory
  ansible.builtin.copy:
    src: "{{ portfolio_clone_path }}/dist/"
    dest: "/var/www/html/"
    remote_src: true

- name: Deploy robots.txt
  ansible.builtin.template:
    src: "robots.txt.j2"
    dest: "/var/www/html/robots.txt"
    owner: "{{ new_admin_user }}"
    group: "{{ new_admin_user }}"
    mode: "0644"
