---

- name: Install certbot with nginx plugin
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes

- name: Create /opt/letsencrypt
  ansible.builtin.file:
    path: /opt/letsencrypt
    state: directory
    owner: root
    mode: "0755"

- name: Deploy renew script
  ansible.builtin.template:
    src: sslcert-renew.sh.j2
    dest: "/opt/letsencrypt/sslcert-renew.sh"
    mode: '0750'

- name: Create SSL certificate
  ansible.builtin.command: "bash /opt/letsencrypt/sslcert-renew.sh"
  ignore_errors: true

